StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{5D3D34059A3A1C18}" {
   Id "M2_Notification_Deletion_Forbidden_Rank"
   Target_en_us "You must have a rank %1 to delete the structure"
   Target_ru_ru "Чтобы удалить постройку, требуется звание %1"
   Status DEVELOPMENT_DONE
   Modified 1564292316
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D3CD6842D76D753}" {
   Id "M2_Notification_Deletion_Forbidden_Resource_Loss"
   Target_en_us "Can't delete the structure, as it will cause %1 supplies loss"
   Target_ru_ru "Нельзя удалить постройку, поскольку это приведет к потере %2 ресурсов"
   Status DEVELOPMENT_DONE
   Modified 1564293733
   Author "winse"
   LastChanged "winse"
  }
  CustomStringTableItem "{5D3D3405F2D70A76}" {
   Id "M2_Notification_Deletion_Forbidden_Time"
   Target_en_us "The structure can be deleted in %1"
   Target_ru_ru "Постройка может быть удалена через %1"
   Status DEVELOPMENT_DONE
   Modified 1564293654
   Author "winse"
   LastChanged "winse"
  }
 }
}